
import Footer from '@/components/mainLayout/footer'
import Header from '@/components/mainLayout/header'
import '@/styles/globals.css'

// import { store } from '@/store/store'
// import { SessionProvider } from 'next-auth/react'
// import { Provider } from 'react-redux'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create neaxt app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <SessionProvider> */}
          {/* <Provider store={store}> */}
          `<Header />
            <div className="flex min-h-screen items-center justify-center">
                {children}
            </div>
            <Footer />
          {/* </Provider> */}
        {/* </SessionProvider> */}
      </body>
    </html>
  )
}
