
import Footer from '@/components/mainLayout/footer'
import Header from '@/components/mainLayout/header'
import '@/styles/globals.css'
import { Providers } from './globalRedux/provider'

// import { SessionProvider } from 'next-auth/react'
// import { Provider } from 'react-redux'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create neaxt app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <SessionProvider> */}
          <Providers>
          `<Header />
            <div className="flex min-h-screen items-center justify-center">
                {children}
            </div>
            <Footer />
          </Providers>
        {/* </SessionProvider> */}
      </body>
    </html>
  )
}
